[projet]
nom = "nol-dotenv"
version = "0.1.0"
entree = "src/lib.nol"
auteur = "daliranas <bastien@languedoc.ovh>"
licence = "MIT"
description = "Chargement de fichiers .env (cle=valeur, commentaires, guillemets) en pur Nolc."

[dependances]
